theme: minima
title: My Practice Blog
author: Tim G
email: tdgesq@verizon.net
description: head meta keywords (for Google search results and feed.xml)
# baseurl:
# social links
twitter_username: none. they call it twitter for a reason!
github_username:  glazart
show_excerpts: true # set to false to remove excerpts on the homepage
